spring:
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:file:~/test
        username: sa
        password:
        driverClassName: org.h2.Driver
    jpa:
        show-sql: true
        open-in-view: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
            format_sql: true
logging:
  level:
    ROOT: error