create table barber_service (duration decimal(21,0) not null, price decimal(38,2) not null, id bigint not null AUTO_INCREMENT, name varchar(255) not null, note varchar(255), primary key (id))
create table barber_shop (id bigint not null AUTO_INCREMENT, address varchar(255), closing_hour varchar(255) not null, end_break_time varchar(255), name varchar(255), opening_hour varchar(255) not null, start_break_time varchar(255), working_day ENUM ('Friday','Monday','Saturday','Sunday','Thursday','Tuesday','Wednesday') not null, primary key (id))
create table client (id bigint not null AUTO_INCREMENT, email varchar(255), name varchar(255) not null, phone varchar(255) not null, primary key (id))
create table payment (amount decimal(38,2) not null, client_id bigint not null, date DATETIME(6) not null, id bigint not null AUTO_INCREMENT, payment_method ENUM ('CASH','CREDIT_CARD','DEBIT_CARD','PIX') not null, primary key (id))
create table schedule (barber_service_id bigint not null, client_id bigint, date DATETIME(6) not null, id bigint not null AUTO_INCREMENT, status ENUM ('CANCELED','COMPLETED','SCHEDULED'), primary key (id))
alter table barber_service add constraint UKiwmk910rx006ymyp4ukrcasix unique (name)
alter table barber_shop add constraint UKjlp0div8j6eg6ip0dfso5cdus unique (working_day)
alter table client add constraint UKbfgjs3fem0hmjhvih80158x29 unique (email)
alter table client add constraint UKqe9dtj732yl9u3oqhhsee4lps unique (phone)
alter table payment add constraint FK3fpanu7q9tijfio491vu0fd0r foreign key (client_id) references client (id)
alter table schedule add constraint FKpx31d1y7t9dknv3x9oo4kgs3l foreign key (barber_service_id) references barber_service (id)
alter table schedule add constraint FKffi483m655f7wqdwp0d4uthf0 foreign key (client_id) references client (id)